# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define :servidorDocker do |servidorDocker|
    servidorDocker.vm.box = "bento/ubuntu-22.04"
    servidorDocker.vm.network :private_network, ip: "192.168.100.10"
    servidorDocker.vm.hostname = "servidorDocker"
  end
end
