# -- mode: ruby --
# vi: set ft=ruby :
$install_puppet = <<-PUPPET
sudo apt-get update -y
sudo apt-get install -y puppet
PUPPET

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
  end
  
  config.vm.define :puppetServer do |puppetServer|
    puppetServer.vm.box = "bento/ubuntu-20.04"
    puppetServer.vm.hostname = "puppetServer"
    puppetServer.vm.network :private_network, ip: "192.168.90.3"
    
    puppetServer.vm.provision "shell", inline: $install_puppet
    
    puppetServer.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.manifest_file = "site.pp"
      puppet.module_path = "puppet/modules"
    end
  end
end