# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define :servidorWeb1 do |servidorWeb1|
    servidorWeb1.vm.box = "bento/ubuntu-22.04"
    servidorWeb1.vm.network :private_network, ip: "192.168.100.7"
    servidorWeb1.vm.hostname = "servidorWeb1"
    servidorWeb1.vm.provision "shell", path: "script.sh"
  end
end
