# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define :servidorWeb2 do |servidorWeb2|
    servidorWeb2.vm.box = "bento/ubuntu-22.04"
    servidorWeb2.vm.network :private_network, ip: "192.168.100.8"
    servidorWeb2.vm.hostname = "servidorWeb2"
    servidorWeb2.vm.provision "shell", path: "script.sh"
  end
end
